### ISSUE TITLE
 Please save the entity before performing this operation!

### ISSUE THREAD

**Issue by PiotrFerenc** [dj-nitehawk/MongoDB.Entities#114]
Hi,
When I try to run Find.

`var result = await DB.Find<T>().ManyAsync(f => f.Users.ID == userId);`

I have error like below:

 Please save the entity before performing this operation!

DB:
![image](https://user-images.githubusercontent.com/30370747/127857899-9dc1a6cc-7c12-43b0-b2ad-79b3aaa0bfbc.png)

Plz help me :) 

PS:
method works good but error is after execution...

`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Please save the entity before performing this operation!
         at MongoDB.Entities.Extensions.ThrowIfUnsaved(String entityID)
         at MongoDB.Entities.Extensions.ThrowIfUnsaved(IEntity entity)
         at MongoDB.Entities.Many`1.ChildrenQueryable(IClientSessionHandle session, AggregateOptions options)
         at MongoDB.Entities.Many`1.GetEnumerator()
         at WebApp.Pages.FloweList.FlowerList.BuildRenderTree(RenderTreeBuilder __builder) in D:\Projekty\FloweList\FlowerList.razor:line 10
         at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
         at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
         at WebApp.Pages.Pages__Host.<ExecuteAsync>b__14_1() in D:\Projekty\Intraflora\Intraflora\Web\WebApp\Pages\_Host.cshtml:line 20
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
         at WebApp.Pages.Pages__Host.ExecuteAsync() in D:\Web\WebApp\Pages\_Host.cshtml:line 5
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext c`
```
    public class User : Entity
    {
      
    }
```
```

    public class MyFlowerList : Entity
    {
        public One<User> Users { get; set; }
        [OwnerSide] public Many<MyFlower> Flowers { get; set; }

        public MyFlowerList()
        {
            this.InitManyToMany(() => Flowers, x => x.FlowerList);
        }
    }
```

```
    public class MyFlower : Entity
    {
        public One<Flower> Flower { get; set; }
        public double Price { get; set; }

        [InverseSide]
        public Many<MyFlowerList> FlowerList { get; set; }

        public MyFlower()
        {
            this.InitManyToMany(() => FlowerList, x => x.Flowers);
        }
    }
```

**Comment by dj-nitehawk** [comment]
hello... i tried to replicate your issue but can't seem to. can you update the following console program and show me how to get the error? usually this error is thrown when you try to access children of an entity instance that doesn't have it's `ID` property populated. more info is given in the docs [here](https://mongodb-entities.com/wiki/Relationships-Referenced.html#one-to-many--many-to-many)

```csharp
using MongoDB.Driver;
using MongoDB.Entities;
using System.Threading.Tasks;

namespace StackOverflow
{
    public class User : Entity { }

    public class MyFlowerList : Entity
    {
        public One<User> User { get; set; }

        [OwnerSide]
        public Many<MyFlower> Flowers { get; set; }

        public MyFlowerList()
        {
            this.InitManyToMany(() => Flowers, x => x.FlowerList);
        }
    }

    public class MyFlower : Entity
    {
        [InverseSide]
        public Many<MyFlowerList> FlowerList { get; set; }

        public MyFlower()
        {
            this.InitManyToMany(() => FlowerList, x => x.Flowers);
        }
    }

    internal static class Program
    {
        private static async Task Main()
        {
            await DB.InitAsync("test");

            var user = new User();
            await user.SaveAsync();

            var flower = new MyFlower();
            await flower.SaveAsync();

            var flowerList = new MyFlowerList { User = user };
            await flowerList.SaveAsync();

            await flower.FlowerList.AddAsync(flowerList);
            await flowerList.Flowers.AddAsync(flower);

            var result = await DB.Find<MyFlowerList>().ManyAsync(x => x.User.ID == user.ID);

            var flowers = await result[0].Flowers.ChildrenQueryable().ToListAsync();
        }
    }
}

```

**Comment by PiotrFerenc** [comment]
I found where is problem.

Blaroz page:
```

<table class="table">
    <thead>
    <tr>
        <th scope="col">Price</th>
 
    </tr>
    </thead>
    <tbody>
   
        **@foreach (var flower in _list.Flowers)  
        {
            <tr>
                <th scope="row">@flower.Price</th>
            </tr>

        }**
    </tbody>
</table>


@page "/Flowers"

@using Infrastructure.Service.FlowerService
@using Microsoft.AspNetCore.Http
@using Core.Domain
@using System.Security.Claims

@attribute [Authorize]

@inject IFlowerService _flowerService;
@inject IHttpContextAccessor _httpContextAccessor


@code {

    MyFlowerList _list = new ();

    
    protected override async Task OnParametersSetAsync()
    {
        if (_httpContextAccessor.HttpContext != null)
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            _list = await _flowerService.GetUserFlowerList(userId);
        }
    }

}
```

**Comment by dj-nitehawk** [comment]
i'm not familiar with blazor but it looks like you might benefit from making your flowerservice return materialized entities like this:
```csharp
public class FlowerService
{
    public async Task<List<MyFlower>> GetUserFlowerListAsync(string UserID)
    {
        var flowerList = await DB
                .Find<MyFlowerList>()
                .Match(fl => fl.User.ID == UserID)
                .ExecuteSingleAsync();

        return await flowerList.Flowers.ChildrenQueryable().ToListAsync();
    }
}
```

**Comment by PiotrFerenc** [comment]
@dj-nitehawk thnks for help!

how I fix ?
```c#

            var flowerList = await DB.Find<MyFlowerList>().ManyAsync(fl => fl.User.ID == userId);

            if (flowerList.Any())
            {
                return await flowerList.First().Flowers.ChildrenQueryable().ToListAsync();
            }
```

**Comment by dj-nitehawk** [comment]
```csharp
public async Task<List<MyFlower>> GetUserFlowerListAsync(string userId)
{
    var flowerList = await DB
            .Find<MyFlowerList>()
            .Match(fl => fl.User.ID == userId)
            .ExecuteFirstAsync();

    if (flowerList is null)
        return new();

    return await flowerList.Flowers.ChildrenQueryable().ToListAsync();
}
```
