### ISSUE TITLE
Library looks not working in blazor (it works great in razor)

### ISSUE THREAD

**Issue by jigarprajapatieastern** [dj-nitehawk/MongoDB.Entities#152]
I using razor with your library, it work absolutely great. but when i used same things into blazor it gives me error like this

`System.AggregateException: One or more errors occurred. (List of configured name servers must not be empty. (Parameter 'servers'))
 ---> System.ArgumentOutOfRangeException: List of configured name servers must not be empty. (Parameter 'servers')
   at DnsClient.LookupClient.QueryInternal(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers)
   at DnsClient.LookupClient.Query(DnsQuestion question)
   at DnsClient.LookupClient.Query(String query, QueryType queryType, QueryClass queryClass)
   at MongoDB.Driver.Core.Misc.DnsClientWrapper.ResolveTxtRecords(String domainName, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Configuration.ConnectionString.Resolve(Boolean resolveHosts, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoUrl.Resolve(Boolean resolveHosts, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClientSettings.FromUrl(MongoUrl url)
   at MongoDB.Driver.MongoClientSettings.FromConnectionString(String connectionString)
   at PJ101.Client.Program.Main(String[] args)
   --- End of inner exception stack trace --- blazor.webassembly.js:1:43413`

![image](https://user-images.githubusercontent.com/82803338/149978185-9be067bb-b5c7-40d4-863a-6b9afd97401d.png)

I use same step in razor and it's work fine

**Comment by dj-nitehawk** [comment]
i'm afraid this has nothing to do with mongodb.entities
it is an exception thrown by the driver due to being unable to resolve dns or something.
i'm not even sure if mongo driver supports client-side blazor.
this so question might offer some insight: https://stackoverflow.com/q/61667534/4368485
