### ISSUE TITLE
Query result is not correct

### ISSUE THREAD

**Issue by li-zheng-hao** [dj-nitehawk/MongoDB.Entities#188]
```csharp
[Fact]
public async Task Test()
{
    // count is 20
    var all = await  DB.Find<CNCPartCost>().Match(it=>true).ExecuteAsync();
    // count is 1
    var filterRes= all.Where(pc =>
        pc.Steps.Count > 0 && pc.Steps.First(s => s.Status == CNCPartCostStatus.Quoted).Time != null).ToList();
    // count is 0
    var res =await  DB.Find<CNCPartCost>().Match(pc =>
            pc.Steps.Count > 0 && pc.Steps.First(s => s.Status == CNCPartCostStatus.Quoted).Time != null)
        .ExecuteAsync();
    // count is 0
    var res2=DB.Collection<CNCPartCost>().Database.GetCollection<CNCPartCost>("cncPartCosts").AsQueryable().Where(pc =>
        pc.Steps.Count > 0 && pc.Steps.First(s => s.Status == CNCPartCostStatus.Quoted).Time != null).ToList();
}
```
Under normal circumstances, the results of `filterRes`、`res`、`res2` should both be 1，and when i check the query log from mongo,i get this:

![image](https://user-images.githubusercontent.com/22129824/197111871-91fd86c5-3ff0-4994-b8d0-7f6a3a1c3edf.png)

I found that the converted pipeline code is not consistent with my linq code，did I do something wrong?

one data that should be returned:

![image](https://user-images.githubusercontent.com/22129824/197112208-6d6d26ce-ade5-4051-be22-87f0a44a0e04.png)

**Comment by dj-nitehawk** [comment]
is this a query that used to work pre-v21? and now it translates differently?

**Comment by li-zheng-hao** [comment]
my version below:
![image](https://user-images.githubusercontent.com/22129824/197113004-fa4c53f4-b67c-40e3-9bd3-5ae6d9e3c464.png)

I will test on the  upgraded version

**Comment by dj-nitehawk** [comment]
if not solved latest version, can you pls provide a repro that i can just copy/paste and debug?

**Comment by li-zheng-hao** [comment]
> if not solved in latest version, can you pls provide a repro that i can just copy/paste and debug?

Yes, if I find that the result is the same after the upgrade, I will write a minimal reproducible sample code and submit it

**Comment by dj-nitehawk** [comment]
also, i think this is a limitation of the mongo driver. it does sometimes have difficulty when querying nested stuff like this which requires workarounds. situation might be improved in latest driver which v21 uses because it comes with their latest LINQ3 translation engine.

**Comment by dj-nitehawk** [comment]
https://www.mongodb.com/docs/mongodb-analyzer/current/

this helps in some cases to see what kind of query is not supported.

**Comment by li-zheng-hao** [comment]
after upgrade to lastest version,i get exception when i run same unittest code:
```csharp
MongoDB.Driver.MongoCommandException: Command find failed: An object representing an expression must have exactly one field: { $gt: [ { $size: "$Steps" }, 0 ], $ne: [ { $let: { vars: { this: { $arrayElemAt: [ { $filter: { input: "$Steps", as: "s", cond: { $eq: [ "$$s.Status", 3 ] } } }, 0 ] } }, in: "$$this.Time" } }, null ] }.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocolAsync[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.ExecuteAsync[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Entities.Find`2.ExecuteAsync(CancellationToken cancellation)
   at Repository层单元测试.Entities库测试.Test() in F:\Code\bjmyBackend\backend_core\FB.UnitTest\Repository单元测试\Entities库测试.cs:line 93
```
it was throw at this line:
```csharp
 var res =await  DB.Find<CNCPartCost>().Match(pc =>
                pc.Steps.Count > 0 && pc.Steps.First(s => s.Status == CNCPartCostStatus.Quoted).Time != null)
            .ExecuteAsync();
```

version info:

![image](https://user-images.githubusercontent.com/22129824/197115224-46876e9d-2061-4184-b15b-5f0823a2e51a.png)

**Comment by dj-nitehawk** [comment]
so yeah it doesn't look like it's a supported way to write the query. send a minimal repro and i'll see if i can help you rewrite it in a valid way.

**Comment by dj-nitehawk** [comment]
also intead of Find<>, try with Queryable<>

**Comment by li-zheng-hao** [comment]
[mongotest.zip](https://github.com/dj-nitehawk/MongoDB.Entities/files/9835845/mongotest.zip)

sample code here

**Comment by dj-nitehawk** [comment]
this works:
```cs
var res = await DB
    .Find<Model>()
    .Match(m => m.NestedModel.Count > 0 &&
                m.NestedModel.Any(nm => nm.Status == 0 && nm.Time != null))
    .ExecuteAsync();
```

**Comment by dj-nitehawk** [comment]
when in doubt, refer to these two links to see what's supported:
http://mongodb.github.io/mongo-csharp-driver/2.18/reference/driver/crud/linq/
http://mongodb.github.io/mongo-csharp-driver/2.18/reference/driver/expressions/

**Comment by li-zheng-hao** [comment]
Wow, very nice solution! thank you very much for your help! I will take the time to read the relevant information
