### ISSUE TITLE
how  to use projecting on page query ?

### ISSUE THREAD

**Issue by li-zheng-hao** [dj-nitehawk/MongoDB.Entities#190]
my test code:
```c#
public class TestModel : Entity
{
    public bool IsDelete { get; set; }
    public string Name { get; set; }
}
public class TestModelDTO:Entity
{
    public string Name { get; set; }
}

[Fact]
public async Task TestProjectPageQuery()
{
    var model=new TestModel() { Name = "123", IsDelete = false };
    await model.SaveAsync();
    // ok
    var res=await DB.Find<TestModel,TestModelDTO>().Match(it=>it.IsDelete==false).ExecuteAsync();
    // error
    var 
dtosPage=await DB.PagedSearch<TestModel, TestModelDTO>()
        .Sort(it=>it.ID,Order.Ascending).Match(it => it.IsDelete == false).PageNumber(1).PageSize(10)
        .ExecuteAsync();
}
```

exception stack :
```
System.ArgumentException
The output type to the last stage was expected to be XXXX.TestModelDTO, but was XXXX.TestModel. (Parameter 'stages')
   at MongoDB.Driver.PipelineStagePipelineDefinition`2.VerifyStages(List`1 stages)
   at MongoDB.Driver.PipelineStagePipelineDefinition`2..ctor(IEnumerable`1 stages, IBsonSerializer`1 outputSerializer)
   at MongoDB.Driver.PipelineDefinition`2.Create(IEnumerable`1 stages, IBsonSerializer`1 outputSerializer)
   at MongoDB.Driver.PipelineDefinition`2.op_Implicit(List`1 stages)
   at MongoDB.Entities.PagedSearch`2.ExecuteAsync(CancellationToken cancellation)
   ...
```

**Comment by li-zheng-hao** [comment]
i dont want to use this:
```c#
.Project(b => new BookListing
                  {
                      BookName = b.Title,
                      AuthorName = b.Author
                  })
```

because I am implementing a repository class like this:
```c#
public class BaseRepository<TDocument> :IBaseRepository<TDocument>  where TDocument:IEntity
{
    public async Task<IPageList<T>> GetPaginatedAsync<T>(Expression<Func<TDocument, bool>> filter, int pageNumber = 1, int pageSize = 50, Action<AggregateOptions>? option = null)
    {
        var pipeline=DB.PagedSearch<TDocument,T>(Transaction?.Session).Match(filter);
        if (option != null)
        {
            pipeline.Option(option);
        }

        var res=await pipeline.Sort(T => T.ID, Order.Ascending).PageSize(pageSize).PageNumber(pageNumber).ExecuteAsync();
        
            pipeline.Option(option);
        }

        var res=await pipeline.Sort(T 
        var pagelist= new PageList<T>(res.Results.ToList(), pageNumber, pageSize,(int)res.TotalCount);
        return pagelist;
    }
}
```
I don't know what fields are in the incoming DTO class, so I don't know how to do the projection，Is there any solution to this problem？

**Comment by dj-nitehawk** [comment]
it's not possible to project to a different type without actually specifying how to project to the other type.
but... you can use a hack/trick like the following:
```cs
var model = new TestModel() { Name = "123", IsDelete = false };
await model.SaveAsync();

var dtosPage = await DB
    .PagedSearch<TestModel, TestModelDTO>()
    .Match(m => m.IsDelete == false)
    .ProjectExcluding(x => new { x._dummyProp }) //everthing other than the dummy property will get projected
    .Sort(m => m.ID, Order.Ascending)
    .PageNumber(1)
    .PageSize(10)
    .ExecuteAsync();

public class TestModel : Entity
{
    public bool IsDelete { get; set; }
    public string Name { get; set; }

    [Ignore]
    public bool _dummyProp { get; set; } //use this to specify an exclusion projection
}

public class TestModelDTO
{
    public string Name { get; set; }
}
```
