### ISSUE TITLE
DB.SaveAsync Error : Must contain at least 1 request 

### ISSUE THREAD

**Issue by li-zheng-hao** [dj-nitehawk/MongoDB.Entities#192]
```c#
[Fact]
public async Task Save()
{
    IEnumerable<CNCPartCost> data = new List<CNCPartCost>()
    {
        new CNCPartCost(){PartName = "1"},
        new CNCPartCost(){PartName = "2"}
    };
    data=data.DistinctByEx(it => it.PartName);
    await DB.SaveAsync(data);
}

public static IEnumerable<TSource> DistinctByEx<TSource, TKey>(
    this IEnumerable<TSource> source,
    Func<TSource, TKey> keySelector)
{
    HashSet<TKey> hash = new HashSet<TKey>();
    return source.Where<TSource>((Func<TSource, bool>) (p => hash.Add(keySelector(p))));
}
```

error info:

```
System.ArgumentException
Must contain at least 1 request. (Parameter 'requests')
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
```

if i use tolist , then it works fine:

```c#
data=data.DistinctByEx(it => it.PartName).ToList();
```

**Comment by li-zheng-hao** [comment]
i see this code in SaveAsync:

```c#
var models = new List<WriteModel<T>>(entities.Count());
foreach (var ent in entities)
{
    if (PrepAndCheckIfInsert(ent))
    {
        models.Add(new InsertOneModel<T>(ent));
    }
    else
    {
        models.Add(new ReplaceOneModel<T>(
            filter: Builders<T>.Filter.Eq(e => e.ID, ent.ID),
            replacement: ent)
        { IsUpsert = true });
    }
}
return session == null
       ? Collection<T>().BulkWriteAsync(models, unOrdBlkOpts, cancellation)
       : Collection<T>().BulkWriteAsync(session, models, unOrdBlkOpts, cancellation);
```

`entities.Count()`  changed the location of iterator, then the later for loops can't read the data

**Comment by li-zheng-hao** [comment]
The cause of the problem has been found : https://github.com/ldqk/Masuit.Tools/issues/77
