### ISSUE TITLE
Delete by lambda expression report errors

### ISSUE THREAD

**Issue by PinkFatMan** [dj-nitehawk/MongoDB.Entities#197]
await DB.DeleteAsync<Book>(b => b.Title.Contains("test21")); 

Unhandled exception. System.InvalidOperationException: ReadName can only be called when State is Name, not when State is EndOfDocument.
   at MongoDB.Bson.IO.BsonReader.ThrowInvalidState(String methodName, BsonReaderState[] validStates)
   at MongoDB.Bson.IO.BsonBinaryReader.ReadName(INameDecoder nameDecoder)
   at MongoDB.Bson.IO.IBsonReaderExtensions.ReadName(IBsonReader reader)
   at MongoDB.Bson.IO.IBsonReaderExtensions.VerifyName(IBsonReader reader, String expectedName)
   at MongoDB.Bson.IO.IBsonReaderExtensions.ReadName(IBsonReader reader, String name)
   at MongoDB.Driver.Linq.Linq3Implementation.Serializers.WrappedValueSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeseria
lizationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext contex
t)
   at MongoDB.Driver.Core.Operations.CursorBatchDeserializationHelper.DeserializeBatch[TDocument](RawBsonArray batch, IBsonSerializer`1 docume
ntSerializer, MessageEncoderSettings messageEncoderSettings)
   at MongoDB.Driver.Core.Operations.FindOperation`1.CreateFirstCursorBatch(BsonDocument cursorDocument)
   at MongoDB.Driver.Core.Operations.FindOperation`1.CreateCursor(IChannelSourceHandle channelSource, IChannelHandle channel, BsonDocument com
mandResult)
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.FindOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken
cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPr
eference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Entities.DB.DeleteAsync[T](FilterDefinition`1 filter, IClientSessionHandle session, CancellationToken cancellation, Collation co
llation)
   at Program.<Main>$(String[] args) in D:\Actor\Actor\Test\Program.cs:line 22
   at Program.<Main>(String[] args)

**Comment by dj-nitehawk** [comment]
can you pls try with `v21.0.2.4-beta`.
if the problem still persists, pls provide a minimalistic repro that includes creation of the data as well.
thanks!

**Comment by PinkFatMan** [comment]
Use v21.0.2.4-beta and still report an error

// See https://aka.ms/new-console-template for more information


using MongoDB.Driver;
using MongoDB.Entities;

await DB.InitAsync("ActorTest", new MongoClientSettings()
{
    Server = new MongoServerAddress("dds-2vcx54ptb8oy0fl2-pub.mongodb.cn-chengdu.rds.aliyuncs.com", 3717),
    Credential = MongoCredential.CreateCredential("admin", "user1150091306", "hejiang123Q")
});

//var book = new Book { Title = "test12" };
//book.ID = "test2";
//await DB.Update<Book>()
//    .MatchID("test2")
//    .Modify(a => a.Title, "The Broken")
//    .ExecuteAsync();

//await DB.DeleteAsync<Book>("test2");
//await DB.DeleteAsync<Book>(book => book.Title.Contains("12")); 
//await DB.DeleteAsync<Book>(b=> b.Title != null);

//long count = await DB.CountAsync<Book>(b=> b.Title == "test21");
//Console.WriteLine(count);

//List<string> distinct = await DB.Distinct<Book, string>()
//    .Property(b => b.Title)
//    .ExecuteAsync();
//Console.WriteLine(distinct.Count);

var book = new Book { Title = "test12" };
book.ID = "test88";
await DB.SaveAsync(book);
await DB.DeleteAsync<Book>(b => b.Title.Contains("test12"));
Console.WriteLine("Hello, World!");


public class Book : Entity
{
    public string Title;
}

**Comment by dj-nitehawk** [comment]
i just tried the following with my local mongodb server and it works just fine.
```cs
await DB.InitAsync("test", "localhost");

var book = new Book
{
    Title = "test12",
    ID = "test88"
};

await DB.SaveAsync(book);

var res = await DB.DeleteAsync<Book>(b => b.Title.Contains("test12"));

Console.WriteLine("delete count: " + res.DeletedCount);
Console.Read();
```
what is the db server you're using? can you try with a local db and see if it throws?

it looks like the latest mongodb driver is not compatible with the server you're using.

the error message indicates that the server responded in an incorrect manner and the driver can't seem to deserialize the response.

by the looks of it, your server doesn't seem to support projections for `find` commands. i tried to do the following using the official driver and i get the same error:
```cs
var coll = db.GetCollection<Book>("Book");
var filter = Builders<Book>.Filter.Where(b => b.Title == "test12");
var projection = Builders<Book>.Projection.Expression(b => b.ID);
var res = await coll.FindAsync<string?>(filter, new() { Projection = projection });
```
the following find command without the projection works fine:
```cs
var filter = Builders<Book>.Filter.Where(b => b.Title == "test12");
var res = await coll.FindAsync(filter);
```

so you might wanna talk to your db providers support to figure out why the find commands with projections don't work.
