### ISSUE TITLE
Getting Exception at InitOneToMany

### ISSUE THREAD

**Issue by atresnjo** [dj-nitehawk/MongoDB.Entities#49]
Hey, I have been getting random exceptions. Those don't always occur, but there are few in my log.

Version: 12.1.2

```csharp
2020-06-12 04:52:55.2098||FATAL|30|   at System.Collections.Generic.HashSet`1.Contains(T item)
   at MongoDB.Entities.Many`1.SetupIndexes(IMongoCollection`1 collection)
   at MongoDB.Entities.Many`1.Init[TParent](TParent parent, String property)
   at MongoDB.Entities.Many`1..ctor(Object parent, String property)
   at MongoDB.Entities.Extensions.InitOneToMany[TChild](IEntity parent, Expression`1 propertyToInit)
```
Throws here

```csharp
public SchoolPlanFileEntry()
{
   this.InitOneToMany(() => SchoolClasses);
}
```

Thanks for the help! :)

**Comment by dj-nitehawk** [comment]
thanks for reporting...
i was unable to reproduce the exception but i switched the implementation to better handle high concurrency situations.
can you give the latest version a try and report back if the error disappeared from your logs.

cheers!

**Comment by atresnjo** [comment]
I've updated to the latest version yesterday, no exceptions so far. Will report back if they occur again, thanks! 👍
